# Generated by Django 4.0.5 on 2022-06-28 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheTranslations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_integrity', models.CharField(max_length=255, unique=True, verbose_name='Data integrity')),
                ('original_data', models.TextField(verbose_name='Original Data')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
            },
        ),
        migrations.CreateModel(
            name='CacheTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2, verbose_name='Language')),
                ('cached_translation', models.TextField(verbose_name='Translated text')),
                ('translation_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_translator.cachetranslations', verbose_name='Parent table')),
            ],
            options={
                'verbose_name': 'Cached translation',
                'verbose_name_plural': 'Cached translations',
            },
        ),
    ]
