# Generated by Django 4.0.5 on 2022-06-28 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_translator', '0003_alter_cachetranslations_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachetranslations',
            name='identifier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
